stages:
  - deploy

deploy_to_server:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh rsync
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - |
      cat <<EOF > ~/.ssh/config
      Host ngrok-server
        HostName $REMOTE_HOST
        Port $REMOTE_PORT
        User $SSH_USER
        IdentityFile ~/.ssh/id_rsa
        StrictHostKeyChecking no
      EOF
    - ssh-keyscan -p $REMOTE_PORT $REMOTE_HOST >> ~/.ssh/known_hosts
  script:
    - echo "Deploying to remote Docker host via SSH/ngrok..."
    - rsync -avz -e "ssh" ./ ngrok-server:/home/noturminesv/projects/gitlab/mahitala-backend
    - |
      ssh ngrok-server 'bash -s' <<'ENDSSH'
        cd /home/noturminesv/projects/gitlab/mahitala-backend
        docker stop mahitala-backend || true
        docker rm mahitala-backend || true
        docker build -t mahitala-backend .
        docker run -d --name mahitala-backend -p 3321:3321 mahitala-backend
      ENDSSH
    - echo "Deployment completed successfully."
  only:
    - production
